In [6]:
import numpy as np
arr = np.array([[ 1,  2,  3],
                [ 3, 45,  6],
                [ 4,  5,  6]])
arr


array([[ 1,  2,  3],
       [ 3, 45,  6],
       [ 4,  5,  6]])

In [21]:
print(arr.T)

[[ 1  3  4]
 [ 2 45  5]
 [ 3  6  6]]


In [24]:
for i in arr.flat: # for print one by one in array
    print(i)

1
2
3
3
45
6
4
5
6


In [26]:
a=np.arange(99)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98


In [28]:
a.nbytes

792

In [7]:
two=np.array([[1,2,3,4,5]])
two

array([[1, 2, 3, 4, 5]])

In [9]:
print(two.max)
print(two.min)
print(two.argsort())


<built-in method max of numpy.ndarray object at 0x113681830>
<built-in method min of numpy.ndarray object at 0x113681830>
[[0 1 2 3 4]]


In [11]:
print(arr.sort())

None
