In [4]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5] )

# Perform an operation
print("Array:", arr)
print("Sum of elements:", np.sum(arr))

Array: [1 2 3 4 5]
Sum of elements: 15


In [5]:
print([arr])

[array([1, 2, 3, 4, 5])]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr[2]

<function int64.any>

In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a[1]

array([4, 5, 6])

In [14]:
a[0]

array([1, 2, 3])

In [15]:
a.shape

(3, 3)

In [16]:
a.dtype

dtype('int64')

In [18]:
a[1,2]=65
a

array([[ 1,  2,  3],
       [ 4,  5, 65],
       [ 7,  8,  9]])

In [19]:
print(a)

[[ 1  2  3]
 [ 4  5 65]
 [ 7  8  9]]


In [24]:
a[1,1]=98
a

array([[ 1,  2,  3],
       [ 4, 98, 98],
       [ 7,  8, 98]])

In [25]:
print(a)

[[ 1  2  3]
 [ 4 98 98]
 [ 7  8 98]]


In [29]:
a[0,1]=8
a

array([[ 7,  8,  3],
       [ 4, 98, 98],
       [ 7,  8, 98]])

In [33]:
a[1,2]=9
a

array([[ 7,  8,  3],
       [ 4, 89,  9],
       [ 7,  8, 98]])

In [34]:
a[1]

array([ 4, 89,  9])

In [35]:
np.array([[1,2,3,4],[5,67,8,9]])

array([[ 1,  2,  3,  4],
       [ 5, 67,  8,  9]])

In [38]:
list=[1,2,3,4]
con=np.array(list)
print(con)
print(type(con))

[1 2 3 4]
<class 'numpy.ndarray'>


In [41]:
print(list)

[1, 2, 3, 4]


In [45]:
t=(1,2,3,4)
a=np.array(t)
print(type(a))

<class 'numpy.ndarray'>


In [57]:
z=np.ones((3,3))
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
a=np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
a=np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
a.shape

(5, 3)

In [59]:
a.dtype

dtype('float64')

In [64]:
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [65]:
print(type(a))

<class 'numpy.ndarray'>


In [66]:
a.shape

(2, 2)

In [67]:
a.dtype

dtype('float64')